name: Java8+ library

on: [push, pull_request]

jobs:
  build-and-test-job:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        experimental: [false]
        include:
          - java: '>11-ea'
            os: ubuntu-latest
            experimental: true

    name: JDK:${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
        run: java -version

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

  github-release-job:
    needs: build-and-test-job
    if: github.repository == 'nbbrd/sandbox' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]
    env:
      DEPLOY_BIN: target/binaries/*

    name: GitHub release on tag
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: Create release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.DEPLOY_BIN }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

  maven-release-job:
    needs: build-and-test-job
    if: github.repository == 'nbbrd/sandbox' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]

    name: Maven release on tag
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy with Maven
        run: mvn -B deploy -Dmaven.test.skip -s ci.settings.xml -P deploy-releases
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}

  maven-snapshot-job:
    needs: build-and-test-job
    if: github.repository == 'nbbrd/sandbox' && github.ref == 'refs/heads/develop'
    strategy:
      matrix:
        java: [11]
        os: [ubuntu-latest]

    name: Maven snapshot on develop
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy with Maven
        run: mvn -B deploy -Dmaven.test.skip -s ci.settings.xml -P deploy-snapshots
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
